allowBuilds:
  '@parcel/watcher': true
  es5-ext: true
  esbuild: true
  sharp: true
  svelte-preprocess: true
  workerd: true

blockExoticSubdeps: true

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - '@parcel/watcher'
  - es5-ext
  - esbuild
  - sharp
  - svelte-preprocess
  - workerd

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
