blockExoticSubdeps: true

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - '@parcel/watcher'
  - es5-ext
  - esbuild
  - svelte-preprocess

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
